### ISSUE TITLE
Add project "analytics" to Transifex sync

### ISSUE THREAD

**Issue by rakekniven** [nextcloud/docker-ci#325]
- [x] App repo: Add .tx folder including config -> @Rello https://github.com/Rello/analytics/issues/202
- [x] App repo: Add ignore file -> @Rello https://github.com/Rello/analytics/issues/202
- [x] App repo: Add l10n folder -> @Rello https://github.com/Rello/analytics/issues/202
- [x] App repo: Invite "nextcloud bot" with write permissions  -> @Rello
- [x] docker-ci: add repo info to config.json -> rakekniven Details: #324
- [x] Sysadmins of NC: Deploy internally to tx sync process -> @blizzz 
- [x] Transifex: New resource should appear -> rakekniven
- [x] Transifex: Do translations and check sync to repo -> rakekniven

**Comment by rakekniven** [comment]
As this is a longer story and still not finished I will summarize here what happened the last 10 days.

The repo has been prepared like always, resource has been added to docker-ci, bot was added to repo with necessary rights.
Someone from NC deployed it internally and sync was triggered.
Nothing happened.
The next morning 6AM CET the sync ran and resource "analytics" showed up nicely at Transifex 🎉 
Normally this is the end but not here 📖. Please readn on.

URL https://www.transifex.com/nextcloud/nextcloud/nextcloud-analytics/ was not loading correctly. I as an project manager was not able to lock/unlock/modify the resource like for the other 165 resources.
The translators are able to use web UI for translating the resource and they started with abnormal speed like always.
Next step was to open an Ticket at Transifex.
Later the next day I received an answer: The word "analytics" caused some trouble. Technically it a resevered word at Transifex. They renamed the resource to "analytics-2021" and it was fine for them.

But not for us because the sync with GitHub was not working.

Transifex is using a "slug" whatever it is. I was able to rename the name to "analytics" and the slug name is "nextcloud-analytics"

<img width="673" alt="Bildschirmfoto 2021-11-22 um 17 44 19" src="https://user-images.githubusercontent.com/2069590/142901268-95a0eab3-9ab6-412e-ad7e-9024fff4ba02.png">

The config file has also been adapted:

https://raw.githubusercontent.com/Rello/analytics/master/.tx/config

But now the sync is still not working.

Whoever has the chance to fix this the hero of the month November 2021.

**Comment by rakekniven** [comment]
🎉 The last try from yesterday has solved it!
